[global]
   workgroup = WORKGROUP
   server string = HomeLab NAS Server
   security = user

   # Compatibilidade de protocolo com PS2 (OPL) e clientes modernos
   server min protocol = NT1
   client min protocol = NT1
   server max protocol = SMB3

   # Autenticação e Ajustes de Criptografia Legada
   lanman auth = yes
   ntlm auth = yes
   raw NTLMv2 auth = yes
   client NTLMv2 auth = no

   # Desativação de assinaturas de pacote (Corrige Erro 310 no OPL)
   server signing = disabled
   smb ports = 445 139

   # Segurança e Filtragem por Subnet
   hosts allow = 192.168.22. 127.0.0.1 100.
   hosts deny = ALL

# Compartilhamento Exclusivo para os Jogos do PS2
[PS2]
   comment = Compartilhamento de ISOs para Open PS2 Loader
   path = /home/ps2
   browseable = yes
   read only = no
   guest ok = yes
   public = yes
   valid users = ps2
   create mask = 0775
   directory mask = 0775
